import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialCompleteSchema1791577338294 implements MigrationInterface {
    name = 'InitialCompleteSchema1791577338294'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "access_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "userId" character varying NOT NULL, "userName" character varying NOT NULL, "userEmail" character varying, "job_title" character varying, "role" character varying NOT NULL DEFAULT 'POS', "status" character varying NOT NULL DEFAULT 'PENDING', "reason" character varying NOT NULL DEFAULT 'OUT_OF_SCHEDULE', "entry_time" character varying, "exit_time" character varying, "attempt_time" character varying NOT NULL, "approved_token" text, "approved_payload" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a543250cab0b6d2eb3a85593d93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userTenantAccessId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, CONSTRAINT "PK_ef53f40c47a666ad8cf8c988003" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_tenant_access" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tenantId" uuid NOT NULL, "role" character varying NOT NULL DEFAULT 'USER', "roles" text DEFAULT '', "isActive" boolean NOT NULL DEFAULT true, "status" character varying NOT NULL DEFAULT 'ACCEPTED', "salaryAmount" numeric(12,2), "salaryPeriod" character varying, "job_title" character varying, "entry_time" character varying, "exit_time" character varying, "lunch_start" character varying, "lunch_end" character varying, CONSTRAINT "PK_1d4bd780abd38cdcb2e7fd31fbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e810a60fffdf12bdcc8094722c" ON "user_tenant_access"  ("userId", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "name" character varying, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'POS', "identification" character varying, "phone" character varying, "is_email_verified" boolean NOT NULL DEFAULT false, "email_verification_code" character varying(6), "email_verification_expires_at" TIMESTAMP, "resetPasswordCode" character varying, "resetPasswordExpires" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saas_payment_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "amount_bs" numeric(12,2), "exchange_rate" numeric(10,2), "payment_method" character varying NOT NULL DEFAULT 'PAGO_MOVIL', "reference" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "reject_reason" text, "months" integer DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_41506ab9be6c09d4df923e63bd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "promoter_commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promoterId" uuid NOT NULL, "tenantId" uuid NOT NULL, "type" character varying(30) NOT NULL DEFAULT 'ACTIVATION', "amountUSD" numeric(10,2) NOT NULL, "saasPaymentReportId" uuid, "status" character varying(30) NOT NULL DEFAULT 'PENDING', "paidAt" TIMESTAMP, "paymentReference" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5f1075c7d007c7917cb4ddafe66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "promoters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "code" character varying(50) NOT NULL, "pagoMovilPhone" character varying, "pagoMovilCedula" character varying, "pagoMovilBank" character varying, "binancePayId" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e866e887a1e5fba414f2f896b28" UNIQUE ("userId"), CONSTRAINT "UQ_9c0a80fbc6cb93bfb63c899bad1" UNIQUE ("code"), CONSTRAINT "REL_e866e887a1e5fba414f2f896b2" UNIQUE ("userId"), CONSTRAINT "PK_7ab4bd7b1b1efeb3d2f8efc180f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c0a80fbc6cb93bfb63c899bad" ON "promoters"  ("code") `);
        await queryRunner.query(`CREATE TABLE "tenant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "status" character varying NOT NULL DEFAULT 'TRIAL', "plan_type" character varying NOT NULL DEFAULT 'REGULAR', "trial_ends_at" TIMESTAMP, "current_period_ends_at" TIMESTAMP, "referred_by_tenant_id" uuid, "referral_code" character varying, "base_price" numeric(10,2) NOT NULL DEFAULT '20', "promoterId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1e2deb18e614893a0f7255f25c1" UNIQUE ("referral_code"), CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8eb9f3e420aa846f30e291960" ON "tenant"  ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_26e4cd6480e6e3a8fdfa1391e3" ON "tenant"  ("status") `);
        await queryRunner.query(`CREATE TABLE "cash_exchanges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "amountBs" numeric(14,2) NOT NULL DEFAULT '0', "amountUSD" numeric(12,2) NOT NULL DEFAULT '0', "exchangeRate" numeric(12,4) NOT NULL DEFAULT '0', "operationType" character varying NOT NULL DEFAULT 'BUY_USD', "source" character varying NOT NULL DEFAULT 'BANCO_BS', "destination" character varying NOT NULL DEFAULT 'CASH_USD', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9b1e327e376eef219f344101cf4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0db104d30980ef097a63e057d0" ON "cash_exchanges"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebc467f9b5ea19d714a7b598e5" ON "cash_exchanges"  ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movement_type_enum" AS ENUM('IN_PURCHASE', 'IN_PRODUCTION', 'OUT_PRODUCTION', 'OUT_SALE', 'LOSS', 'IN', 'OUT')`);
        await queryRunner.query(`CREATE TABLE "stock_movement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rawMaterialId" uuid NOT NULL, "type" "public"."stock_movement_type_enum" NOT NULL, "quantity" numeric(12,2) NOT NULL DEFAULT '0', "totalCost" numeric(12,2) NOT NULL DEFAULT '0', "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "tenantId" uuid, CONSTRAINT "PK_9fe1232f916686ae8cf00294749" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d55dbedd2c517d9e6a8cbf12c" ON "stock_movement"  ("rawMaterialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_847183dfeae32546c826f20401" ON "stock_movement"  ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e098ef21abe6da166d9fa3b49" ON "stock_movement"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_670ac123ae6ca56a0a202b8739" ON "stock_movement"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7264694032acb150d30c5218b1" ON "stock_movement"  ("tenantId", "rawMaterialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_046c51f5baf7a0d189e06bad01" ON "stock_movement"  ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "raw_material" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "unit" character varying NOT NULL, "costPerUnit" numeric(12,4) NOT NULL DEFAULT '0', "stockQuantity" numeric(12,4) NOT NULL DEFAULT '0', "minStockAlert" numeric(12,4) NOT NULL DEFAULT '5', "allowAsExtra" boolean NOT NULL DEFAULT false, "extraPriceType" character varying DEFAULT 'COST', "extraPriceValue" numeric(12,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "tenantId" uuid, CONSTRAINT "PK_78620c6a699438f30545519c86b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a280e6bf273bfae9a726ca9703" ON "raw_material"  ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_53ffde10f61d4456fb84d377b0" ON "raw_material"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2508dafade1464400f8fe62d9" ON "raw_material"  ("tenantId", "name") `);
        await queryRunner.query(`CREATE TABLE "recipe_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "rawMaterialId" uuid NOT NULL, "quantity" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_bbaf66acc7e7c6dc3d1bc42a247" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "identification" character varying, "notes" text, "total_visits" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_27167753bd0bf7696209fc2271" ON "customers"  ("tenantId", "identification") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c0d50bb04cf7976e922b5781d" ON "customers"  ("tenantId", "phone") `);
        await queryRunner.query(`CREATE TABLE "delivery_zone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "feePrice" numeric(12,4) NOT NULL DEFAULT '0', "tenantId" uuid, CONSTRAINT "PK_8a390f981b91bfca80510b43511" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('PENDING', 'PREPARING', 'READY', 'IN_TRANSIT', 'PARTIALLY_DELIVERED', 'DELIVERED', 'CANCELED', 'CERRADO_CON_PERDIDA', 'SOLICITUD_ENCARGO', 'PENDIENTE_PAGO', 'CANCELADO_PROVEEDOR')`);
        await queryRunner.query(`CREATE TYPE "public"."order_paymentstatus_enum" AS ENUM('PARTIAL', 'PENDING', 'PAID', 'REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_deliverymethod_enum" AS ENUM('IN_STORE', 'PICKUP', 'DELIVERY')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerName" character varying NOT NULL, "customerPhone" character varying NOT NULL, "identification" character varying, "customerId" uuid, "customerAddress" character varying, "notes" character varying, "tableNumber" character varying, "requestedDeliveryDate" TIMESTAMP, "status" "public"."order_status_enum" NOT NULL DEFAULT 'PENDING', "paymentStatus" "public"."order_paymentstatus_enum" NOT NULL DEFAULT 'PENDING', "paymentReported" boolean NOT NULL DEFAULT false, "paymentProofUrl" character varying, "paymentRejectedReason" character varying, "paymentMethod" character varying, "splitPayments" jsonb, "deliveryMethod" "public"."order_deliverymethod_enum" NOT NULL DEFAULT 'IN_STORE', "deliveryZoneId" uuid, "deliveryFee" numeric(12,4) NOT NULL DEFAULT '0', "discountAmount" numeric(12,4) NOT NULL DEFAULT '0', "discountType" character varying, "discountValue" numeric(12,4), "totalCost" numeric(12,4) NOT NULL DEFAULT '0', "netProfit" numeric(12,4) NOT NULL DEFAULT '0', "totalAmount" numeric(12,4) NOT NULL DEFAULT '0', "pagoMovilRef" character varying, "pagoMovilPhone" character varying, "pagoMovilCedula" character varying, "pagoMovilBank" character varying, "amountBs" numeric(12,4), "exchangeRate" numeric(12,4), "usdReceived" numeric(12,4), "changeAmount" numeric(12,4), "changeAmountBs" numeric(12,4), "changeMethod" character varying, "changeRef" character varying, "puntoRef" character varying, "puntoBank" character varying, "binanceRef" character varying, "transferRef" character varying, "transferBank" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, "abonosTotal" numeric(12,4) NOT NULL DEFAULT '0', "abonosHistory" json, "employeeId" uuid, "deliveryUserId" uuid, "driverId" uuid, "linkedReservationId" character varying, "offlineId" character varying, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a9573d6a1fb982772a9123320" ON "order"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3995ab3a03cf2b54b0999f75a3" ON "order"  ("paymentStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bb07d3c6e225d75d8418380f1" ON "order"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7853202400ba8726242baa7a91" ON "order"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bde46c5c57a69f2cb02d02b17" ON "order"  ("linkedReservationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2ba056b43aaf2d67bd69f240b" ON "order"  ("offlineId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6092d24f773f28f1ac9dd48ce8" ON "order"  ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae9d226da0dc2887b05734fb58" ON "order"  ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "order_item_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imageUrl" text NOT NULL, "orderItemId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f407c25d5daec0d7bbf7e526709" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "productId" uuid NOT NULL, "productName" character varying, "quantity" integer NOT NULL, "deliveredQuantity" integer NOT NULL DEFAULT '0', "unitPrice" numeric(12,2) NOT NULL DEFAULT '0', "unitCost" numeric(12,4) NOT NULL DEFAULT '0', "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "removedIngredients" text, "addedExtras" text, "hasModifications" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_646bf9ece6f45dbe41c203e06e" ON "order_item"  ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_904370c093ceea4369659a3c81" ON "order_item"  ("productId") `);
        await queryRunner.query(`CREATE TABLE "production_batch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "quantity" integer NOT NULL, "totalCost" numeric(12,4) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, CONSTRAINT "PK_259b9cb2f2094ae62d18868624b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "category" character varying, "images" text, "salePrice" numeric(12,2) NOT NULL DEFAULT '0', "estimatedCost" numeric(12,2) NOT NULL DEFAULT '0', "duration_minutes" integer, "assignedStaffIds" text, "stockQuantity" numeric(12,4) NOT NULL DEFAULT '0', "cost" numeric(12,2) NOT NULL DEFAULT '0', "stock" numeric(12,2) NOT NULL DEFAULT '0', "is_service" boolean NOT NULL DEFAULT false, "product_type" character varying DEFAULT 'REVENTA', "physicalStock" numeric(12,4) NOT NULL DEFAULT '0', "isCombo" boolean NOT NULL DEFAULT false, "isPreAssembled" boolean NOT NULL DEFAULT false, "availabilityType" character varying NOT NULL DEFAULT 'INMEDIATO', "isSupplierPreorder" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "tenantId" uuid, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22cc43e9a74d7498546e9a63e7" ON "product"  ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_d71ac3a30622a475df871b5513" ON "product"  ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_08293ca31a601d3cd0228120bc" ON "product"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a0cf25cd8232a154d1cce2641" ON "product"  ("tenantId", "category") `);
        await queryRunner.query(`CREATE TABLE "combo_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comboId" uuid NOT NULL, "componentId" uuid NOT NULL, "quantity" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_adb6455f8fabc75656764672d88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_type_enum" AS ENUM('CLIENT_TO_BUSINESS', 'BUSINESS_TO_PLATFORM')`);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."feedback_type_enum" NOT NULL, "content" text NOT NULL, "clientName" character varying, "clientPhone" character varying, "rating" integer, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."investments_type_enum" AS ENUM('INVERSION_EXTERNA', 'REINVERSION_GANANCIA')`);
        await queryRunner.query(`CREATE TABLE "investments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "negocioId" uuid, "type" "public"."investments_type_enum" NOT NULL DEFAULT 'INVERSION_EXTERNA', "amountUSD" numeric(12,2) NOT NULL DEFAULT '0', "amountBS" numeric(12,2) NOT NULL DEFAULT '0', "exchangeRate" numeric(12,4) NOT NULL DEFAULT '1', "description" text, "date" date NOT NULL DEFAULT ('now'::text)::date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a1263853f1a4fb8b849c1c9aff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0db10e1bbae7283d98d46f63b6" ON "investments"  ("negocioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b5b1d47007af286f3582da85d" ON "investments"  ("negocioId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7336f86ffaed5e19831ddc4d50" ON "investments"  ("negocioId", "date") `);
        await queryRunner.query(`CREATE TABLE "operating_expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "amount" numeric(12,2) NOT NULL DEFAULT '0', "paymentMethod" character varying, "category" character varying NOT NULL DEFAULT 'GENERAL', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, CONSTRAINT "PK_1447e00c7341a5fa9c09ae56666" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5fad0e9124e0d64e5665e2cae3" ON "operating_expenses"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_20a8fd2c39db279864b0664cae" ON "operating_expenses"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_49084e64e0d4ef1ddbe31cb1d8" ON "operating_expenses"  ("tenantId", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_3cabfe0e1073e80b40519074a6" ON "operating_expenses"  ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "platform_config" ("id" character varying NOT NULL DEFAULT 'default', "companyBank" character varying, "companyCedula" character varying, "companyPhone" character varying, "companyAccountNumber" character varying, "companyAccountHolder" character varying, "binancePayId" character varying, "binanceEmail" character varying, "defaultMonthlyPrice" numeric(10,2) NOT NULL DEFAULT '20', "defaultTrialDays" integer NOT NULL DEFAULT '15', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_992be521a533da5953589a85fcf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identifier" character varying NOT NULL, "endpoint" text NOT NULL, "p256dh" text NOT NULL, "auth" text NOT NULL, "negocioId" character varying, "role" character varying NOT NULL DEFAULT 'CUSTOMER', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10e30a5f283cb7bf93edb40866" ON "push_subscriptions"  ("identifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b5e71bbbf039bdf3f719d2d97" ON "push_subscriptions"  ("negocioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9dd28265fcaa0b8761e52829e" ON "push_subscriptions"  ("negocioId", "identifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d70ef34af71f3f127fe146179" ON "push_subscriptions"  ("negocioId", "role") `);
        await queryRunner.query(`CREATE TYPE "public"."reservation_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELED')`);
        await queryRunner.query(`CREATE TYPE "public"."reservation_paymentstatus_enum" AS ENUM('PARTIAL', 'PENDING', 'PAID', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "reservation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerName" character varying NOT NULL, "customerPhone" character varying, "identification" character varying, "customerId" uuid, "date" date NOT NULL, "time" TIME NOT NULL, "numberOfPeople" integer, "serviceId" character varying, "serviceName" character varying, "tableNumber" character varying, "employeeId" uuid, "employeeName" character varying, "status" "public"."reservation_status_enum" NOT NULL DEFAULT 'PENDING', "paymentStatus" "public"."reservation_paymentstatus_enum" NOT NULL DEFAULT 'PENDING', "paymentReported" boolean NOT NULL DEFAULT false, "paymentProofUrl" character varying, "paymentRejectedReason" character varying, "totalAmount" numeric(12,4) NOT NULL DEFAULT '0', "abonosTotal" numeric(12,4) NOT NULL DEFAULT '0', "abonosHistory" jsonb, "notes" text, "referralSource" character varying, "rescheduleStatus" character varying, "originalTime" character varying, "originalDate" character varying, "imageUrl" text, "orderId" character varying, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_48b1f9922368359ab88e8bfa525" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d10f9471f0072b3911128f8fd5" ON "reservation"  ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc3a8a4798468a78e25561db8b" ON "reservation"  ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_29be1e5ad1e641d6966b30aa9b" ON "reservation"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7301aff02b1010e190ca2dda0c" ON "reservation"  ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c349e8b52ff38fdc4d5c924ca9" ON "reservation"  ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b02c963d61829f26589739f16" ON "reservation"  ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd930f9fab1ae8395ee97bac3a" ON "reservation"  ("tenantId", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."salary_advances_status_enum" AS ENUM('PENDIENTE', 'DESCONTADO')`);
        await queryRunner.query(`CREATE TABLE "salary_advances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "negocioId" uuid, "amountUSD" numeric(12,2) NOT NULL DEFAULT '0', "amountBS" numeric(12,2) NOT NULL DEFAULT '0', "exchangeRate" numeric(12,4) NOT NULL DEFAULT '1', "reason" text, "date" date NOT NULL DEFAULT ('now'::text)::date, "status" "public"."salary_advances_status_enum" NOT NULL DEFAULT 'PENDIENTE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_325edae8cea0d58b9a8bba7dc30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac02a49e874e4dda7fb8bd369d" ON "salary_advances"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0d9848a39829fcc71d0df0f5a" ON "salary_advances"  ("negocioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61987b3caec1c820a6dfce76cb" ON "salary_advances"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f81fc12d098bc5b4ce57d6a20" ON "salary_advances"  ("negocioId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1916d5d8484e046dd776dd15e3" ON "salary_advances"  ("negocioId", "status") `);
        await queryRunner.query(`CREATE TABLE "settings" ("id" character varying NOT NULL, "exchangeRateBs" numeric(12,4) NOT NULL DEFAULT '40', "exchangeRateMode" character varying NOT NULL DEFAULT 'BCV', "manualExchangeRate" numeric(12,4), "currencySymbol" character varying NOT NULL DEFAULT 'Bs.', "ratesCache" jsonb, "companyBank" character varying, "companyCedula" character varying, "companyPhone" character varying, "companyAccountNumber" character varying, "companyAccountHolder" character varying, "binancePayId" character varying, "binanceEmail" character varying, "binancePhone" character varying, "acceptCashUsd" boolean NOT NULL DEFAULT true, "acceptPagoMovil" boolean NOT NULL DEFAULT true, "acceptCardPos" boolean NOT NULL DEFAULT false, "acceptBinance" boolean NOT NULL DEFAULT false, "acceptTransfer" boolean NOT NULL DEFAULT false, "allowPartialPayments" boolean NOT NULL DEFAULT true, "minDepositPercentage" numeric(5,2) NOT NULL DEFAULT '0', "allowCashierBypassDeposit" boolean NOT NULL DEFAULT true, "featureDelivery" boolean NOT NULL DEFAULT true, "featureCustomerSchedules" boolean NOT NULL DEFAULT false, "featureRecipes" boolean NOT NULL DEFAULT false, "featureBuySell" boolean NOT NULL DEFAULT false, "featureProduction" boolean NOT NULL DEFAULT true, "requireApprovalAlways" boolean NOT NULL DEFAULT false, "allowNegativeStock" boolean NOT NULL DEFAULT false, "featureShowCatalog" boolean NOT NULL DEFAULT true, "bookingRequireService" boolean NOT NULL DEFAULT true, "bookingAllowStaffSelection" boolean NOT NULL DEFAULT false, "businessHours" jsonb, "services" jsonb, "slotInterval" integer NOT NULL DEFAULT '30', "bookingMaxAdvanceDays" integer DEFAULT '365', "endOfDayOffsetHours" integer NOT NULL DEFAULT '0', "bookingRequireDeposit" boolean NOT NULL DEFAULT false, "bookingDepositPercentage" numeric(5,2) NOT NULL DEFAULT '0', "themePrimaryColor" character varying, "themeHeaderColor" character varying, "initialCashUSD" numeric(12,2) NOT NULL DEFAULT '0', "initialBankBs" numeric(12,2) NOT NULL DEFAULT '0', "initialDigitalUSD" numeric(12,2) NOT NULL DEFAULT '0', "tenantId" uuid, CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "work_schedule" ADD CONSTRAINT "FK_f45962b40fbe8b151476dbf09f8" FOREIGN KEY ("userTenantAccessId") REFERENCES "user_tenant_access"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_tenant_access" ADD CONSTRAINT "FK_6583dfb1bbad86aaa7de17bb22f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_tenant_access" ADD CONSTRAINT "FK_ada03627606c770ae2156a33706" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saas_payment_reports" ADD CONSTRAINT "FK_339ba63038a9da0ee0084576bb0" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" ADD CONSTRAINT "FK_307991c43f21dfdce50d755e6d6" FOREIGN KEY ("promoterId") REFERENCES "promoters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" ADD CONSTRAINT "FK_57ac8ccfdc6ce87f1263f6d6d47" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" ADD CONSTRAINT "FK_77a77d7908fafb103c0bcf97f7c" FOREIGN KEY ("saasPaymentReportId") REFERENCES "saas_payment_reports"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promoters" ADD CONSTRAINT "FK_e866e887a1e5fba414f2f896b28" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant" ADD CONSTRAINT "FK_2663f2514fd6538e3bab84bdbc9" FOREIGN KEY ("promoterId") REFERENCES "promoters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_exchanges" ADD CONSTRAINT "FK_0db104d30980ef097a63e057d00" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_0d55dbedd2c517d9e6a8cbf12c2" FOREIGN KEY ("rawMaterialId") REFERENCES "raw_material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_670ac123ae6ca56a0a202b87398" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "raw_material" ADD CONSTRAINT "FK_53ffde10f61d4456fb84d377b00" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_item" ADD CONSTRAINT "FK_e3dac4000afd3471e67cc0480f9" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_item" ADD CONSTRAINT "FK_99698d2fec6051616ad88cdbecf" FOREIGN KEY ("rawMaterialId") REFERENCES "raw_material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_37c1a605468d156e6a8f78f1dc5" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_zone" ADD CONSTRAINT "FK_e5cb202c33a7820dc47c2078b64" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_c978af3b7b7f9c078f80cf6a392" FOREIGN KEY ("deliveryZoneId") REFERENCES "delivery_zone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_7853202400ba8726242baa7a916" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_9b451675cd9fe227a0dd5120e53" FOREIGN KEY ("employeeId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_7eeba87ab436612e0250bdbceec" FOREIGN KEY ("deliveryUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_8cbf856839ddca842f21b804a91" FOREIGN KEY ("driverId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_media" ADD CONSTRAINT "FK_393c63f0b9e9dd985142c9a66a1" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_media" ADD CONSTRAINT "FK_a7c8851937dc442a563d4f52aec" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_batch" ADD CONSTRAINT "FK_a6ee17a1cd43b1075da973a4012" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_batch" ADD CONSTRAINT "FK_259fb9ce8917865f6513d1c2a81" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_08293ca31a601d3cd0228120bc9" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "combo_item" ADD CONSTRAINT "FK_d18c56a6186aba174d286364ee5" FOREIGN KEY ("comboId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "combo_item" ADD CONSTRAINT "FK_3150ec25f31a3eab9d974b2142e" FOREIGN KEY ("componentId") REFERENCES "product"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_1b8d0642e09df4550b01185a8ba" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investments" ADD CONSTRAINT "FK_0db10e1bbae7283d98d46f63b65" FOREIGN KEY ("negocioId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operating_expenses" ADD CONSTRAINT "FK_20a8fd2c39db279864b0664cae8" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_7dce8a5a6907476eba30fedde91" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_ecb8639e53747f1aa3828603fc7" FOREIGN KEY ("employeeId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_c349e8b52ff38fdc4d5c924ca91" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_advances" ADD CONSTRAINT "FK_ac02a49e874e4dda7fb8bd369d0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_advances" ADD CONSTRAINT "FK_c0d9848a39829fcc71d0df0f5af" FOREIGN KEY ("negocioId") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_1fa41192963d6275ba8952f02a9" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_1fa41192963d6275ba8952f02a9"`);
        await queryRunner.query(`ALTER TABLE "salary_advances" DROP CONSTRAINT "FK_c0d9848a39829fcc71d0df0f5af"`);
        await queryRunner.query(`ALTER TABLE "salary_advances" DROP CONSTRAINT "FK_ac02a49e874e4dda7fb8bd369d0"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_c349e8b52ff38fdc4d5c924ca91"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_ecb8639e53747f1aa3828603fc7"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_7dce8a5a6907476eba30fedde91"`);
        await queryRunner.query(`ALTER TABLE "operating_expenses" DROP CONSTRAINT "FK_20a8fd2c39db279864b0664cae8"`);
        await queryRunner.query(`ALTER TABLE "investments" DROP CONSTRAINT "FK_0db10e1bbae7283d98d46f63b65"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_1b8d0642e09df4550b01185a8ba"`);
        await queryRunner.query(`ALTER TABLE "combo_item" DROP CONSTRAINT "FK_3150ec25f31a3eab9d974b2142e"`);
        await queryRunner.query(`ALTER TABLE "combo_item" DROP CONSTRAINT "FK_d18c56a6186aba174d286364ee5"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_08293ca31a601d3cd0228120bc9"`);
        await queryRunner.query(`ALTER TABLE "production_batch" DROP CONSTRAINT "FK_259fb9ce8917865f6513d1c2a81"`);
        await queryRunner.query(`ALTER TABLE "production_batch" DROP CONSTRAINT "FK_a6ee17a1cd43b1075da973a4012"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "order_item_media" DROP CONSTRAINT "FK_a7c8851937dc442a563d4f52aec"`);
        await queryRunner.query(`ALTER TABLE "order_item_media" DROP CONSTRAINT "FK_393c63f0b9e9dd985142c9a66a1"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_8cbf856839ddca842f21b804a91"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_7eeba87ab436612e0250bdbceec"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_9b451675cd9fe227a0dd5120e53"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_7853202400ba8726242baa7a916"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_c978af3b7b7f9c078f80cf6a392"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_124456e637cca7a415897dce659"`);
        await queryRunner.query(`ALTER TABLE "delivery_zone" DROP CONSTRAINT "FK_e5cb202c33a7820dc47c2078b64"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_37c1a605468d156e6a8f78f1dc5"`);
        await queryRunner.query(`ALTER TABLE "recipe_item" DROP CONSTRAINT "FK_99698d2fec6051616ad88cdbecf"`);
        await queryRunner.query(`ALTER TABLE "recipe_item" DROP CONSTRAINT "FK_e3dac4000afd3471e67cc0480f9"`);
        await queryRunner.query(`ALTER TABLE "raw_material" DROP CONSTRAINT "FK_53ffde10f61d4456fb84d377b00"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_670ac123ae6ca56a0a202b87398"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_0d55dbedd2c517d9e6a8cbf12c2"`);
        await queryRunner.query(`ALTER TABLE "cash_exchanges" DROP CONSTRAINT "FK_0db104d30980ef097a63e057d00"`);
        await queryRunner.query(`ALTER TABLE "tenant" DROP CONSTRAINT "FK_2663f2514fd6538e3bab84bdbc9"`);
        await queryRunner.query(`ALTER TABLE "promoters" DROP CONSTRAINT "FK_e866e887a1e5fba414f2f896b28"`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" DROP CONSTRAINT "FK_77a77d7908fafb103c0bcf97f7c"`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" DROP CONSTRAINT "FK_57ac8ccfdc6ce87f1263f6d6d47"`);
        await queryRunner.query(`ALTER TABLE "promoter_commissions" DROP CONSTRAINT "FK_307991c43f21dfdce50d755e6d6"`);
        await queryRunner.query(`ALTER TABLE "saas_payment_reports" DROP CONSTRAINT "FK_339ba63038a9da0ee0084576bb0"`);
        await queryRunner.query(`ALTER TABLE "user_tenant_access" DROP CONSTRAINT "FK_ada03627606c770ae2156a33706"`);
        await queryRunner.query(`ALTER TABLE "user_tenant_access" DROP CONSTRAINT "FK_6583dfb1bbad86aaa7de17bb22f"`);
        await queryRunner.query(`ALTER TABLE "work_schedule" DROP CONSTRAINT "FK_f45962b40fbe8b151476dbf09f8"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1916d5d8484e046dd776dd15e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f81fc12d098bc5b4ce57d6a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61987b3caec1c820a6dfce76cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0d9848a39829fcc71d0df0f5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac02a49e874e4dda7fb8bd369d"`);
        await queryRunner.query(`DROP TABLE "salary_advances"`);
        await queryRunner.query(`DROP TYPE "public"."salary_advances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd930f9fab1ae8395ee97bac3a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b02c963d61829f26589739f16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c349e8b52ff38fdc4d5c924ca9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7301aff02b1010e190ca2dda0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29be1e5ad1e641d6966b30aa9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc3a8a4798468a78e25561db8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d10f9471f0072b3911128f8fd5"`);
        await queryRunner.query(`DROP TABLE "reservation"`);
        await queryRunner.query(`DROP TYPE "public"."reservation_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reservation_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d70ef34af71f3f127fe146179"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9dd28265fcaa0b8761e52829e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b5e71bbbf039bdf3f719d2d97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10e30a5f283cb7bf93edb40866"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "platform_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cabfe0e1073e80b40519074a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49084e64e0d4ef1ddbe31cb1d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20a8fd2c39db279864b0664cae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fad0e9124e0d64e5665e2cae3"`);
        await queryRunner.query(`DROP TABLE "operating_expenses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7336f86ffaed5e19831ddc4d50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b5b1d47007af286f3582da85d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0db10e1bbae7283d98d46f63b6"`);
        await queryRunner.query(`DROP TABLE "investments"`);
        await queryRunner.query(`DROP TYPE "public"."investments_type_enum"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_type_enum"`);
        await queryRunner.query(`DROP TABLE "combo_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a0cf25cd8232a154d1cce2641"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08293ca31a601d3cd0228120bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d71ac3a30622a475df871b5513"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22cc43e9a74d7498546e9a63e7"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "production_batch"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_904370c093ceea4369659a3c81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_646bf9ece6f45dbe41c203e06e"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TABLE "order_item_media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae9d226da0dc2887b05734fb58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6092d24f773f28f1ac9dd48ce8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2ba056b43aaf2d67bd69f240b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bde46c5c57a69f2cb02d02b17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7853202400ba8726242baa7a91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bb07d3c6e225d75d8418380f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3995ab3a03cf2b54b0999f75a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a9573d6a1fb982772a9123320"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_deliverymethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "delivery_zone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c0d50bb04cf7976e922b5781d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27167753bd0bf7696209fc2271"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "recipe_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2508dafade1464400f8fe62d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53ffde10f61d4456fb84d377b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a280e6bf273bfae9a726ca9703"`);
        await queryRunner.query(`DROP TABLE "raw_material"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_046c51f5baf7a0d189e06bad01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7264694032acb150d30c5218b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_670ac123ae6ca56a0a202b8739"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e098ef21abe6da166d9fa3b49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_847183dfeae32546c826f20401"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d55dbedd2c517d9e6a8cbf12c"`);
        await queryRunner.query(`DROP TABLE "stock_movement"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movement_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebc467f9b5ea19d714a7b598e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0db104d30980ef097a63e057d0"`);
        await queryRunner.query(`DROP TABLE "cash_exchanges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26e4cd6480e6e3a8fdfa1391e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8eb9f3e420aa846f30e291960"`);
        await queryRunner.query(`DROP TABLE "tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c0a80fbc6cb93bfb63c899bad"`);
        await queryRunner.query(`DROP TABLE "promoters"`);
        await queryRunner.query(`DROP TABLE "promoter_commissions"`);
        await queryRunner.query(`DROP TABLE "saas_payment_reports"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e810a60fffdf12bdcc8094722c"`);
        await queryRunner.query(`DROP TABLE "user_tenant_access"`);
        await queryRunner.query(`DROP TABLE "work_schedule"`);
        await queryRunner.query(`DROP TABLE "access_request"`);
    }

}
